export const data = [
  {
    No: 0,
    name: "Cornstarch",
    serving_size: "100 g",
    calories: 381,
    total_fat: "0.1g",
    cholesterol: "0",
    sodium: "9.00 mg",
    protein: "0.26 g",
    sugars: "0.00 g",
  },
  {
    No: 1,
    name: "Nuts, pecans",
    serving_size: "100 g",
    calories: 691,
    total_fat: "72g",
    cholesterol: "0",
    sodium: "0.00 mg",
    protein: "9.17 g",
    sugars: "3.97 g",
  },
  {
    No: 2,
    name: "Eggplant, raw",
    serving_size: "100 g",
    calories: 25,
    total_fat: "0.2g",
    cholesterol: "0",
    sodium: "2.00 mg",
    protein: "0.98 g",
    sugars: "3.53 g",
  },
  {
    No: 3,
    name: "Teff, uncooked",
    serving_size: "100 g",
    calories: 367,
    total_fat: "2.4g",
    cholesterol: "0",
    sodium: "12.00 mg",
    protein: "13.30 g",
    sugars: "1.84 g",
  },
  {
    No: 4,
    name: "Sherbet, orange",
    serving_size: "100 g",
    calories: 144,
    total_fat: "2g",
    cholesterol: "1mg",
    sodium: "46.00 mg",
    protein: "1.10 g",
    sugars: "24.32 g",
  },
  {
    No: 5,
    name: "Cauliflower, raw",
    serving_size: "100 g",
    calories: 25,
    total_fat: "0.3g",
    cholesterol: "0",
    sodium: "30.00 mg",
    protein: "1.92 g",
    sugars: "1.91 g",
  },
  {
    No: 6,
    name: "Taro leaves, raw",
    serving_size: "100 g",
    calories: 42,
    total_fat: "0.7g",
    cholesterol: "0",
    sodium: "3.00 mg",
    protein: "4.98 g",
    sugars: "3.01 g",
  },
  {
    No: 7,
    name: "Lamb, raw, ground",
    serving_size: "100 g",
    calories: 282,
    total_fat: "23g",
    cholesterol: "73mg",
    sodium: "59.00 mg",
    protein: "16.56 g",
    sugars: "0.00 g",
  },
  {
    No: 8,
    name: "Cheese, camembert",
    serving_size: "100 g",
    calories: 300,
    total_fat: "24g",
    cholesterol: "72mg",
    sodium: "842.00 mg",
    protein: "19.80 g",
    sugars: "0.46 g",
  },
  {
    No: 9,
    name: "Vegetarian fillets",
    serving_size: "100 g",
    calories: 290,
    total_fat: "18g",
    cholesterol: "0",
    sodium: "490.00 mg",
    protein: "23.00 g",
    sugars: "0.80 g",
  },
  {
    No: 10,
    name: "PACE, Picante Sauce",
    serving_size: "100 g",
    calories: 25,
    total_fat: "0g",
    cholesterol: "0",
    sodium: "781.00 mg",
    protein: "0.00 g",
    sugars: "6.25 g",
  },
  {
    No: 11,
    name: "Goji berries, dried",
    serving_size: "100 g",
    calories: 349,
    total_fat: "0.4g",
    cholesterol: "0",
    sodium: "298.00 mg",
    protein: "14.26 g",
    sugars: "45.61 g",
  },
  {
    No: 12,
    name: "Mango nectar, canned",
    serving_size: "100 g",
    calories: 51,
    total_fat: "0.1g",
    cholesterol: "0",
    sodium: "5.00 mg",
    protein: "0.11 g",
    sugars: "12.45 g",
  },
  {
    No: 13,
    name: "Crackers, rusk toast",
    serving_size: "100 g",
    calories: 407,
    total_fat: "7.2g",
    cholesterol: "78mg",
    sodium: "253.00 mg",
    protein: "13.50 g",
    sugars: "0",
  },
  {
    No: 14,
    name: "Chicken, boiled, feet",
    serving_size: "100 g",
    calories: 215,
    total_fat: "15g",
    cholesterol: "84mg",
    sodium: "67.00 mg",
    protein: "19.40 g",
    sugars: "0.00 g",
  },
  {
    No: 15,
    name: "Quail, raw, meat only",
    serving_size: "100 g",
    calories: 134,
    total_fat: "4.5g",
    cholesterol: "70mg",
    sodium: "51.00 mg",
    protein: "21.76 g",
    sugars: "0",
  },
  {
    No: 16,
    name: "Pie, lemon, fried pies",
    serving_size: "100 g",
    calories: 316,
    total_fat: "16g",
    cholesterol: "0",
    sodium: "374.00 mg",
    protein: "3.00 g",
    sugars: "0",
  },
  {
    No: 17,
    name: "Peppers, raw, jalapeno",
    serving_size: "100 g",
    calories: 29,
    total_fat: "0.4g",
    cholesterol: "0",
    sodium: "3.00 mg",
    protein: "0.91 g",
    sugars: "4.12 g",
  },
  {
    No: 18,
    name: "Winged bean tuber, raw",
    serving_size: "100 g",
    calories: 148,
    total_fat: "0.9g",
    cholesterol: "0",
    sodium: "35.00 mg",
    protein: "11.60 g",
    sugars: "0",
  },
  {
    No: 19,
    name: "Salami, turkey, cooked",
    serving_size: "100 g",
    calories: 172,
    total_fat: "9.2g",
    cholesterol: "76mg",
    sodium: "1107.00 mg",
    protein: "19.20 g",
    sugars: "1.12 g",
  },
  {
    No: 20,
    name: "Grapes, raw, muscadine",
    serving_size: "100 g",
    calories: 57,
    total_fat: "0.5g",
    cholesterol: "0",
    sodium: "1.00 mg",
    protein: "0.81 g",
    sugars: "0",
  },
  {
    No: 21,
    name: "Nuts, raw, ginkgo nuts",
    serving_size: "100 g",
    calories: 182,
    total_fat: "1.7g",
    cholesterol: "0",
    sodium: "7.00 mg",
    protein: "4.32 g",
    sugars: "0",
  },
  {
    No: 22,
    name: "Spices, ground, savory",
    serving_size: "100 g",
    calories: 272,
    total_fat: "5.9g",
    cholesterol: "0",
    sodium: "24.00 mg",
    protein: "6.73 g",
    sugars: "0",
  },
  {
    No: 23,
    name: "Candies, sesame crunch",
    serving_size: "100 g",
    calories: 516,
    total_fat: "33g",
    cholesterol: "0",
    sodium: "167.00 mg",
    protein: "11.60 g",
    sugars: "31.17 g",
  },
  {
    No: 24,
    name: "Cheese, low fat, cream",
    serving_size: "100 g",
    calories: 201,
    total_fat: "15g",
    cholesterol: "54mg",
    sodium: "359.00 mg",
    protein: "7.85 g",
    sugars: "5.82 g",
  },
];
